### ISSUE TITLE
Create behavior for lessons steps

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#1]
#### Description

Following the wire frame, we need to code the behavior for each step. Each dot on the left should represent a step, with the color changing if that step is complete or not.

This task could most likely use some additional endpoints available from the How to City API. Lets have a good discussion about what is needed.
#### Files

js/instructions.js
#### Tools Needed

HTML, CSS, JQuery, Bootstrap
#### Screenshot

![htc_lessonwireframes_071213](https://f.cloud.github.com/assets/3219885/791161/c796f4e8-eb3a-11e2-89d0-fd442b9adaad.jpg)
![htc_lessonwireframes_0712132](https://f.cloud.github.com/assets/3219885/791162/ccf8010c-eb3a-11e2-926c-7a6597aa9469.jpg)
#### Tips
- [ ] Use $.getJSON to call http://howtocity.herokuapp.com/api/v1/lessons/1 to get the steps.
- [ ] Use http://twitter.github.io/bootstrap/javascript.html#scrollspy or a variation of it to give a visual indicator of where in the lesson we are.

**Comment by anselmbradford** [comment]
I submitted a pull request (https://github.com/codeforamerica/howtocity-web/pull/2) that adds some modular structure to the JS to (hopefully) make is easier to work with. As is all the var declarations will get attached to the global scope. This wraps all the code in an "instructions" object (aka a JS module) that will live at window.instructions and it also creates private (accessible within the module only) and public (accessible from the outside) methods/properties. Happy to help with working with this structure if needed.

**Comment by ondrae** [comment]
I'm working on this one in the steps_behavior branch.

**Comment by arielkennan** [comment]
In progress visual design: 
![bizfriendly_lessonsteps_072513](https://f.cloud.github.com/assets/3219885/859971/2212d82e-f590-11e2-85bd-19ac8f9bf634.gif)

**Comment by arielkennan** [comment]
Dots for all your dotty needs: 
![green_bigdot](https://f.cloud.github.com/assets/3219885/866196/9786af7c-f65d-11e2-8536-58e5838e5ef3.gif)
![green_smalldot](https://f.cloud.github.com/assets/3219885/866197/9943abb2-f65d-11e2-9911-1cdce0f5fdc3.gif)
![gray_smalldot](https://f.cloud.github.com/assets/3219885/866198/9ac664f2-f65d-11e2-8097-cd95aae45818.gif)

**Comment by arielkennan** [comment]
Logo with no text (150 x100 pixels) 
![bizfriendly_weblogo_notext](https://f.cloud.github.com/assets/3219885/874228/4738c0b0-f887-11e2-9d04-43ccf23b5a94.gif)

**Comment by arielkennan** [comment]
The missing light green dot 
![ltgreen_smalldot](https://f.cloud.github.com/assets/3219885/920836/f97634b4-fee6-11e2-8073-3aafb1dbd938.gif)
