### ISSUE TITLE
Create the "rate me" widget

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#10]
#### Description

Following the wireframe, we need to code the rate me widget that appears on every lesson. 
No design love yet, we just need all the various divs and whatnot to exist.
#### Tools Needed

HTML, CSS, JQuery, Bootstrap
#### Screenshot

![htc_lessonwireframes_071213](https://f.cloud.github.com/assets/3219885/791183/724f61d6-eb3b-11e2-9f17-8780962dfcdc.jpg)
![htc_lessonwireframes_0712135](https://f.cloud.github.com/assets/3219885/791184/7504bfac-eb3b-11e2-92a8-532c74d1b9a7.jpg)

**Comment by arielkennan** [comment]
Visual Design 
![bizfriendly_lessonsteps_rateme1_072513](https://f.cloud.github.com/assets/3219885/860591/969c8fa6-f5ad-11e2-9978-2d8523c5d71b.gif)
![bizfriendly_lessonsteps_rateme2_072513](https://f.cloud.github.com/assets/3219885/860592/969e93e6-f5ad-11e2-9fb3-d4ac8de70ece.gif)

**Comment by ondrae** [comment]
Working on this under the "rating" branch.
