### ISSUE TITLE
Service page - Lesson Ordering

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#107]
The lessons on a service page show up in a different order every time. We should be able to control the order.
- [ ] Grab all the lessons then order.
- [ ] Start by ordering alphabetically

**Comment by lorenanicole** [comment]
Are you still soliciting help on this feature?

**Comment by ondrae** [comment]
Hello @lorenanicole. Yeah any help you can offer to help polish BizFriendly is most appreciated.

I'm taking off the beginner friendly label though cause it might be hard to do. Might be.

There are two ways I see doing it:
1. The easiest way is probably in javascript. In `service.js` you can sort the lessons by `id` or alphabetically. Probably do it right at the beginning of `_lessonTable()`
2. You could change the order of how the API returns the lessons over in [bizfriendly-api](https://github.com/codeforamerica/bizfriendly-api/blob/master/bizfriendly/models.py#L76). Problem is we are attaching the lessons to the service through a SQLAlchemy backref. It looks like its [hard to order them](http://stackoverflow.com/questions/6750251/sqlalchemy-order-by-on-relationship-for-join-table). Thats just my first glance though.

**Comment by lorenanicole** [comment]
@ondrae quick question - do you have an endpoint that I can batch lesson stats look ups at?
Specifically - [the api endpoint http://app.bizfriend.ly/api/v1/userlessons](https://github.com/codeforamerica/bizfriendly-web/blob/gh-pages/js/service.js#L63) seems to handle only one lesson query at a time. If you have an endpoint that supports multiple lesson look ups that would be quite useful! Else I have an alternate solution in mind. Thanks!

**Comment by ondrae** [comment]
It's just one at a time, sorry. I think that's why it's in an each loop. You can hopefully do the sorting before that loop begins though. 

I'm going to be offline till Tuesday, so sorry if my responses are slow.

**Comment by lorenanicole** [comment]
No worries. I have a PR pretty ready to go. Looks like you don't have tests
care if I add some in (Jasmine)?

I can make another PR for tests of course.

Lorena :-)
On Wednesday, January 14, 2015, Andrew Hyder notifications@github.com
wrote:

> It's just one at a time, sorry. I think that's why it's in an each loop.
> You can hopefully do the sorting before that loop begins though.
> 
> I'm going to be offline till Tuesday, so sorry if my responses are slow.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codeforamerica/bizfriendly-web/issues/107#issuecomment-70027985
> .

## 

---

Lorena Mesa
_www.lorenamesa.com http://www.lorenamesa.com/_

"If you wish to make apple pie from scratch, you must first invent the
universe," - Carl Sagan

Please stop
 before printing this email unnecessarily, _think green_!!!

**Comment by ondrae** [comment]
Hi @lorenanicole how'd it work out?

Tests! Yes please! I have a [bunch of tests](https://github.com/codeforamerica/bizfriendly-api/blob/master/tests.py) on the API side, I just did't know Jasmine at all.

**Comment by lorenanicole** [comment]
@ondrae sorry about that - yes I have it wrapped up! Just need to get a PR issued :-) I didn't start on tests as of _yet_ but I can!

**Comment by lorenanicole** [comment]
@ondrae PR issued (finally ha!).

**Comment by ondrae** [comment]
Great work @lorenanicole 

I had never seen `$.when.apply` before. Thanks for teaching me something new.
