### ISSUE TITLE
Add Back to Top links

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#108]
#### Description

On the learn page, add a back to top links for each skill.
See #73

**Comment by nickjellings** [comment]
Do you still want this updated as outlined on the #73 mockup? If so, it might be easier to implement if the "Back to Top" link was either directly above or below the horizontal rule.

Alternatively, there are some jQuery plugins that handle the "back to top" functionality as well (see: http://markgoodyear.com/labs/scrollup/)

Thoughts?

**Comment by ondrae** [comment]
As light weight as possible. BizFriendly already has a crazy amount of floating windows and popups, that I really don't to add anymore. The users of the site are somewhat new to the internet, we don't want to have too much confusing UI.

Simple links back up top, without smooth scrolling is what we're looking for. Having them over the horizontal rule would look best, but any where is helpful.

**Comment by nickjellings** [comment]
See #180

**Comment by nickjellings** [comment]
No rush, just checking in to see if the proposed solution in the pull request seemed to match what was expected? Thx!

**Comment by ondrae** [comment]
Those are perfect! I never knew about the [adjacent sibling selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_selectors) until you used it here.

Thanks
![giphy](https://cloud.githubusercontent.com/assets/595778/4295881/0158f12e-3def-11e4-8c8f-2296ed0e8814.gif)
