### ISSUE TITLE
Google feedback form as modal

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#119]
Have the form be embedded in a modal instead of a separate link

**Comment by arielkennan** [comment]
Form link: https://docs.google.com/a/codeforamerica.org/forms/d/1-0s2k_gpkNDXWRpYYbzltFNaRT0FEOv2--gIwxGGZWU/viewform

**Comment by ondrae** [comment]
It didn't work well as a modal. Couldn't get the width to work right, and the scrolling was awkward. Really didn't work as a modal from the instructions window too.

I added as link to a new tab.
