### ISSUE TITLE
Lesson builder: need to be able to edit "open" button link additional times

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#133]
Currently only lets you edit that link once, should be able to click it again in the builder to enter a new link.

**Comment by ondrae** [comment]
Look for where we hide the open popover. I did this on purpose back when to avoid other problems. I'll need to test if they still exist or if there is another way to keep being able to edit the url.

The relevant code is in js/teach.js

```
$("#open").click(function(){
           ...
              $("#open").popover("hide");
           ...
          })
```
