### ISSUE TITLE
Letter boxing on new vimeo videos 

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#137]
Somethings up with the new vimeo vids and the responsive code. Try changing the heights on their containers.

**Comment by ondrae** [comment]
Duplicate of #146

**Comment by arielkennan** [comment]
Still getting them on Facebook vid. I looked into this a bit last week when I was doing some content updates, and I think it's something to do with responsive trying to adjust to the div. YouTube works fine, but no matter what, I was still getting them on this Vimeo vid. Any other hints?

**Comment by ondrae** [comment]
Fixed on staging. A whole bunch of tickets will close when we transfer over to production. 

Andrew Hyder
2013 Code from America Fellow
@hackyourcity

**Comment by arielkennan** [comment]
Awesome, you're the best :)
