### ISSUE TITLE
Sign In links on mobile

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#138]
Whoa, they are in the wrong place. Something up with doing position relative in the CSS and the col-xs-\* in bootstrap. 

Try firing them above the logo? I've tried a few things and no obvious fix to make them look good at all resolutions.

**Comment by ondrae** [comment]
#### Pics

![photo 1](https://f.cloud.github.com/assets/595778/1855227/feeb40b8-7729-11e3-85d2-069055d83044.PNG)
![photo 2](https://f.cloud.github.com/assets/595778/1855228/fef942ee-7729-11e3-992a-2ae58c62a6fd.PNG)

#### Description

We use Bootstrap 3 for our header. Its all wrapped in a navbar element so its a little finicky.

#### Files

_includes/header.html

**Comment by louh** [comment]
It has partially something to do with the way things are floated around (floats! use sparingly!) and an over-reliance on Bootstrap to control responsive styling for an un-Bootstrappy navigation. I really want to go through and rebuild some of the structure and CSS, but that's a much larger project.
