### ISSUE TITLE
Fix margins on About page

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#145]
Should match marches on Learn.html

**Comment by ondrae** [comment]
#### Description

The layout of About.html was a little rushed. We could use some cleaning it up. 

#### Files

about.html

#### Tips

Most of the site uses the Bootstrap3 classes to set up the grid and margins. `<div class="col-sm-offset-1 col-md-offset-1 col-lg-offset-1">`
The about page is missing these.

**Comment by codeatlanta** [comment]
Do you still need help on this?

**Comment by ondrae** [comment]
Yes! Any improvements to the About page would be helpful. We're going up for some for more partnerships soon, so this page we'll be getting some critical views in October.

**Comment by nickjellings** [comment]
see pull request  #179

Thx.
