### ISSUE TITLE
Review colors across CSS & all pages

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#15]
![bizfriendly_colorguide_072513](https://f.cloud.github.com/assets/3219885/860645/1c40a874-f5b1-11e2-8cb3-264fcaa6c862.gif)

**Comment by ainsleywagon** [comment]
Hi @arielkennan! I played with the color scheme a little bit and looked at adding a lighter orange, lightened the gray a bit, and then made the green a little bluer to make it a direct split complement to your logo orange.
![howtocityweb-colorscheme-11](https://f.cloud.github.com/assets/1807325/888864/fc32c478-fa14-11e2-8c99-f9797c2eb2da.png)
I thought the lighter orange could be a good secondary button option, that was a little softer and not so close to a 'danger' button color, also in application on your icons:
![screen shot 2013-07-31 at 3 13 56 pm](https://f.cloud.github.com/assets/1807325/888893/69f2db60-fa15-11e2-97d3-9eda09f86949.png)
![screen shot 2013-07-31 at 3 14 06 pm](https://f.cloud.github.com/assets/1807325/888894/6d4208a4-fa15-11e2-8f39-61482936499c.png)
Here's the 'bluer green' in application on your Lesson Maker page and I also liked the idea of bringing back a colored gradient like in some of the early wireframes of the lesson step type page:
![screen shot 2013-07-31 at 3 15 03 pm](https://f.cloud.github.com/assets/1807325/888910/ab00d65c-fa15-11e2-8b6c-c1207ccf5598.png)
(Also in above screenshot you can see I sloppily photoshopped a lighter gray navbar, but not so sure it's any improvement on what you already have)
![screen shot 2013-07-31 at 3 17 06 pm](https://f.cloud.github.com/assets/1807325/888921/d8aabc80-fa15-11e2-9700-d4bf9c6b998f.png)

**Comment by ondrae** [comment]
Wow! @ainsleywagon this is great. Thanks for looking at our project. Ariel is out of town for a few days, so expect a response to your ideas here next week. 

I was just looking for a good lighter orange to use as button down state. Very appreciated.

**Comment by ainsleywagon** [comment]
@ondrae no problem, my pleasure! Thanks for letting me poke around on here, I'll continue to peek in at things I could help with.

**Comment by arielkennan** [comment]
@ainsleywagon Thanks for checking out our project! I really dig the light orange and lighter gray. I'd had a peachy color when we were doing logo development and hadn't figured out how to fully incorporate it. I'd like to keep our original green. The new one is a little too teal for my taste, however I do appreciate the attention to detail in color theory :) 

We'll be launching our alpha soon and would love for you to check it out. 

![bizfriendly_colorguide_080513](https://f.cloud.github.com/assets/3219885/908234/1058c8c4-fd87-11e2-9b01-42bd8a201ee0.gif)

**Comment by ty10r** [comment]
imho, the FF8C66 orange is a drastic improvement for things like link-text hover shadowing. I don't know much about color theory, but I felt that FF4000 was a harsh contrast when put directly over the blue and grey like in a link context.

**Comment by ainsleywagon** [comment]
@arielkennan cool! Glad the lighter orange and gray are helpful. You're totally right, coming back to it the teal green isn't contrasting enough with the existing blue (especially to serve its purpose as a 'green light go!'). Fun to peek in on this project, I'd love to check out the alpha! 

@ty10r - yeah, having a lighter option is good for those link contrasts on blue and gray. Also @arielkennan's mention of a peachy color sounds really nice...

**Comment by arielkennan** [comment]
Added new darker blue 
![bizfriendly_colorguide_080613](https://f.cloud.github.com/assets/3219885/913847/365d44da-fe24-11e2-9000-fda5ef8ec494.gif)

**Comment by arielkennan** [comment]
One more update with the addition of the lighter orange: 
![bizfriendly_colorguide_092513](https://f.cloud.github.com/assets/3219885/1228116/73a19082-279e-11e3-988e-7dccf08b1803.png)
