### ISSUE TITLE
ie9 form bug

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#151]
Internet Explorer 9 doesn't display the the helper text on our forms. 
##### IE9

![screen shot 2013-12-26 at 7 22 08 pm](https://f.cloud.github.com/assets/595778/1813101/3bb04534-6ea6-11e3-98a3-b36be28b7bd5.png)
##### Every other browser

![screen shot 2013-12-26 at 7 23 29 pm](https://f.cloud.github.com/assets/595778/1813103/546d936a-6ea6-11e3-8891-adf6f1113da1.png)
#### Files

new-service.html
#### Tips
- [ ] Find an ie9 polyfill
- [ ] Have labels on the forms instead of interior text

**Comment by ondrae** [comment]
Try this polyfill
https://github.com/jamesallardice/Placeholders.js

**Comment by louh** [comment]
+1 on polyfill.
