### ISSUE TITLE
Sign in alert color

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#152]
#### Description

When successfully logged in, the alert box doesn't change to the green color if its already set to red.
#### Reproduce
1. Log in with bad credentials to http://bizfriend.ly/signin.html. A red alert should appear.
2. Then log in with good credentials. The box remains red.
   ![screen shot 2013-12-27 at 2 27 23 pm](https://f.cloud.github.com/assets/595778/1816631/7b29035e-6f46-11e3-9ab7-fb30fb7c260e.png)
#### Files

js/BfUser.js

_signedIn()
#### Tips
- [ ] Remove the alert-danger class when a 200 is returned.

**Comment by arielkennan** [comment]
This is handled a little bit differently in the sign in overlay design, see #94. Do you think we'll be able to implement that in January dev?
