### ISSUE TITLE
Correct scaling/cropping service page image?

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#155]
Noticed today that the service pages that have images embedded are cropping the images (See http://bizfriend.ly/service.html?29 & http://bizfriend.ly/service.html?8) when responsive to different sizes, and event at 100% on my laptop. Both of these images are cropped to our recommended size 600 x 338. Could we have them scale at different responsive scales rather than crop? Would like to confirm this ASAP with doing content outreach with the cities/states so we get assets that are the right size.

**Comment by louh** [comment]
This is easy enough when the image is just an image tag, as in http://bizfriend.ly/service.html?29 - just set the width of the image to 100% of the parent div. When the media object is an iframe (as in http://bizfriend.ly/service.html?8) that's a lot harder - iframe contents aren't meant to scale like an image is. Apparently there are hacks that would make it possible but I would question whether it's just easier to display the contents as an image and not as an iframe at all.

I'll issue a pull request for the image fix, so at least you can see it working part of the time.

**Comment by ondrae** [comment]
Check out http://staging.bizfriend.ly/service.html?29 to see that its working.

**Comment by arielkennan** [comment]
Perfect! Thanks!
