### ISSUE TITLE
Skill & Service Creation Polish

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#161]
**Form Styling**
- [x] Save draft button style should be dark blue with white text, mouseover to light blue (same as lesson builder)
- [x] Section headers such as "Service Information" and "Points to Keep in Mind" should be Open Sans 700, Dark Blue, 18 px
- [x] Style Image Upload / Video Upload text to Open Sans 700, Dark Blue, 14 px

**Submission Modal**
- [x] Review text style for first line to see if we can normalize the spacing
- [x] "Create Another" button text should not have an underline 
- [x] Skill modal missing a "See What You've Created" button 

**Copy Edit**
- [x] On Service form, for video embed, make instruction in box read "Copy and paste a Vimeo or YouTube embed code with size set to 600 x 338"
- [x] On profile, skills should be called "skill" rather than "category". I think category is fine on a db level, but we should be consistent on the front end for users.

**Comment by arielkennan** [comment]
- [x] Add terms of agreement to skill page 
- [x] Add terms of agreement to service page

**Comment by ondrae** [comment]
All the design changes are up on Staging. Haven't written the check to see if the terms of agreement are actually agreed too. Gotta go out for the night though.

**Comment by arielkennan** [comment]
Looks great! 

Please also add the "Copy and paste a Vimeo or YouTube embed code with size set to 600 x 338." to the actual box where you paste it, where it currently just says "Copy and paste a Vimeo embed code."

Also found one more style thing for skills/services while testing today. If there's an error in the form, the error message gets a little crazy with the buttons and terms. I recommend opening up the space above the buttons/terms to allow for the error message to sit nicely in there. Here's what it currently looks like: 
![screen shot 2014-01-21 at 10 16 54 am](https://f.cloud.github.com/assets/3219885/1964573/67ab9ea0-82af-11e3-92ab-32e32549666d.png)

**Comment by ondrae** [comment]
Fixed this one too.
