### ISSUE TITLE
Lesson Builder: Step order jumbled 

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#166]
Steps to reproduce (I think): 
- Create new lesson, add a variety of steps 
- Preview lesson 
- After previewing lesson lost ability to delete elements and also the skill/service dropdowns went back to their default 
- Saved lesson as draft (didn't get a modal) 
- Went to profile and opened lesson to edit 
- Steps now jumbled (jumps from 1 to 10 then 2)

Looks like this: 
![screen shot 2014-01-14 at 11 44 29 pm](https://f.cloud.github.com/assets/3219885/1917642/df5d50f2-7d9f-11e3-853d-34550b92b28c.png)

Also see 
http://bizfriend.ly/lesson-builder.html?49

**Comment by arielkennan** [comment]
I rebuilt this lesson this morning and had the same thing happen again. Perhaps something with saving each step? It goes from step 1 to the congrats step. Issue appeared after submitting and then reopening to edit. 

Check out: http://bizfriend.ly/lesson-builder.html?51

**Comment by ondrae** [comment]
I've fixed the step ordering bugs. Not the preview or modal bugs yet though. Check it out on staging.

**Comment by ondrae** [comment]
Fixed the bugs that happened when previewing. Haven't been able to reproduce the modal not appearing. Can you try it out @arielkennan ? Do it on http://staging.bizfriend.ly which is currently pointing to our production backend.

**Comment by arielkennan** [comment]
Step ordering fixed! Moving the modal bug convo back to #162
