### ISSUE TITLE
Inoviceable logo

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#167]
![screen shot 2014-01-15 at 11 59 57 am](https://f.cloud.github.com/assets/595778/1924261/a5d3bbde-7e1f-11e3-82d0-e4d9cbbd26f4.png)

**Comment by arielkennan** [comment]
I uploaded this as a logo when testing creating services. Somehow replaced the Invoiceable one?

**Comment by ondrae** [comment]
I bet you used the same file name.

I can fix this by appending the date to the file name when it gets uploaded.

Andrew Hyder ::
Developer Relations Engineer
2013 Code For America Fellow
@hackyourcity http://twitter.com/hackyourcity

**Comment by arielkennan** [comment]
Yup! That's what happened. I just fixed it for Invoiceable. Will leave the issue open so you can append the date. Good catch!
