### ISSUE TITLE
Broken Moo lesson

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#173]
#### Description

On the Moo lesson, when I click the Open button, it brings me to http://us.moo.com/create/design.php?uuid=f2f40574-d26c-42a9-a818-df61f30ebd5b&showPlaceholderText=1&sideType=details# which looks like this:
![screen shot 2014-01-25 at 9 59 31 am](https://f.cloud.github.com/assets/595778/2002267/067c590a-85eb-11e3-8c88-2c0218a8464f.png)

I tried it in several browsers.

Also, where should we capture these types of issues? Github with a new content label? The feedback form? Email?

**Comment by arielkennan** [comment]
Well, that's frustrating! I think it saves a cookie or something so it takes me to the right place, but indeed wasn't working in other browsers. I copied the link this time directly from where they link to the design tool on their website and it should now be fixed. 

Also created a content label on here. Definitely the easiest place to track/record issues. 

Thanks for catching this one!
