### ISSUE TITLE
Test site on all browsers

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#18]
#### Description

We are piling on the jQuery and Bootstrap functions. We need to know what browsers we are excluding.
#### Skills Needed

Javascript, Testing
#### Tips
- [x] Try out a browser simulator. Something like http://www.browserstack.com/

**Comment by mwichary** [comment]
We have an account on BrowserStack.

**Comment by max-mapper** [comment]
another easy way is to write tap compatible tests (i like https://npmjs.org/package/tape) and then you can get a [testling](https://ci.testling.com/) badge to put in the readme e.g. https://ci.testling.com/maxogden/browser-request

![](https://ci.testling.com/maxogden/browser-request.png)

**Comment by ondrae** [comment]
Windows XP, 7 & IE 10, Firefox - Popup windows overlap slightly.
![screen shot 2013-08-21 at 6 27 58 pm](https://f.cloud.github.com/assets/595778/1005868/2bf9088c-0aca-11e3-85a8-e23d6667aa9e.png)

Windows XP, 7 & Chrome - Popups are fullscreen. I can do a work around for instructions, yet nothing I can do when we popup a third party site. I've got a Stackoverflow question up.
http://stackoverflow.com/questions/18370627/new-popup-windows-on-google-chrome-for-windows-are-always-the-full-screen-width
