### ISSUE TITLE
Cannot sign up with mymail.university.edu account

### ISSUE THREAD

**Issue by jenjac24** [codeforamerica/bizfriendly-web#187]
Change the signup criteria to allow more than one period in the email address.

**Comment by ondrae** [comment]
Done in https://github.com/codeforamerica/bizfriendly-api/commit/c014e58494b4bdbbb63955a1f402bbf11f136b1f. 

Thanks for all of these issues. I've got BizFriend.ly on a slow burn for both improvements and lesson making.
