### ISSUE TITLE
Business Name "Null"

### ISSUE THREAD

**Issue by jenjac24** [codeforamerica/bizfriendly-web#189]
When you first create your account, if you do not enter a business name it appears as "null" (under your account name) until you enter something.  After you have entered something in the business name field, the space where it said null underneath your name fills with your business name, but if you delete it after that then the field is empty.

**Comment by ondrae** [comment]
Nice find. It was the profile description that was coming back as `null`, yet it wasn't wrapped in an if statement like the rest of the info.
