### ISSUE TITLE
Need to disable site when on mobile.

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#19]
#### Description

Our current design won't work on mobile devices. We need to let the user know that before they start.
#### Files

index.html
#### Tools Needed

HTML, jQuery, Bootstrap
#### Tips
- [ ] Add the code here to the frontpage. http://stackoverflow.com/questions/3514784/what-is-the-best-way-to-detect-a-handheld-device-in-jquery
- [ ] Have a modal popup explaining why it doesn't work on mobile yet. http://twitter.github.io/bootstrap/2.3.2/javascript.html#modals

**Comment by dvidsilva** [comment]
why doesn't it work in mobile, we can use media queries to alter the information displayed and help the user, or am i missing something?

**Comment by ondrae** [comment]
Hi @dvidsilva, thanks for checking out our project. [Our app](http://cfakc.tumblr.com/app) is intended to walk small business through simple tasks on web services. Our current design is going to have two windows pop up next to each other. One window is the web service itself, like Yelp or something, with the other window being our interactive instructions. 

So, for now, I need to warn any users that they can't use the lessons on mobile. In the future we'd like to design a mobile version. I have lots of ideas about how that may work and will write them in another Github issue one day.

Also, I love Bogota. [This](https://foursquare.com/v/salvo-patria/4dfd3186ae6033b2a47762b6) was my favorite restaurant.

**Comment by ondrae** [comment]
I added a little alert() if someone visits from a mobile device.
