### ISSUE TITLE
Implement hover states

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#27]
Related to #15 
![bizfriendly_hoverstates_080613](https://f.cloud.github.com/assets/3219885/913857/58d446a8-fe24-11e2-994b-1edeceb8172f.gif)
![bizfriendly_colorguide_080613](https://f.cloud.github.com/assets/3219885/913859/5aaec11a-fe24-11e2-9a23-ccf0cfcc4a4d.gif)

**Comment by arielkennan** [comment]
Hey @ainsleywagon, any interest in helping us implement this in the next couple days? We'd love your help! Assign the issue to yourself, if so. Thanks!

**Comment by ainsleywagon** [comment]
@arielkennan Tootally! I'd love to. Can you (or someone) add me to the codeforamerica group so I can assign myself the issue? I don't currently have that option.

**Comment by arielkennan** [comment]
Hey @dthompson can you help with getting @ainsleywagon access? Thanks!

**Comment by ondrae** [comment]
Hey @ainsleywagon, instead of granting special permissions, just submit a [pull request](https://github.com/codeforamerica/howtocity-web#submitting-a-pull-request). Its the standard way to collaborate on projects like these. 

Even though we can't assign this issue to you on Github, we'll know you are working on it. It's all yours!

**Comment by ainsleywagon** [comment]
@ondrae @arielkennan sounds good!

**Comment by arielkennan** [comment]
Thanks, @ainsleywagon for your awesome work! We reviewed and merged, with a few slight tweaks. 

@ondrae - here's those icons in blue for the HP
![learn_icon_blue](https://f.cloud.github.com/assets/3219885/933365/4637db9e-0055-11e3-9879-9f9225487c6e.png)
![teach_icon_blue](https://f.cloud.github.com/assets/3219885/933366/48e11dc4-0055-11e3-9864-b1ba7297cd74.png)
![connect_icon_blue](https://f.cloud.github.com/assets/3219885/933367/4bb85d78-0055-11e3-841d-63717d100000.png)
