### ISSUE TITLE
Create the homepage

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#3]
#### Description

Following the wireframe, we need to code the home page for our site. No design love yet, we just need all the various divs and whatnot to exist.

Homepage should also include the header and footer that are used throughout the site. 
#### Files

index.html
#### Tools Needed

HTML, CSS, Bootstrap
#### Screenshot

![htc_homepage071213](https://f.cloud.github.com/assets/3219885/791149/6434a9c2-eb3a-11e2-9c6f-b36ac28dba7b.jpg)

**Comment by arielkennan** [comment]
Here's the visual design for the homepage: 
![bizfriendly_mockups_071613_optc](https://f.cloud.github.com/assets/3219885/836943/88e03f24-f2fc-11e2-9916-1cf40e27900f.gif)

Here's the logo & icon assets(they're white w transparent backgrounds): 
![bizfriendly_weblogo](https://f.cloud.github.com/assets/3219885/836945/a15a7d08-f2fc-11e2-8503-6297743193cc.png)
Teach
![teach_icon](https://f.cloud.github.com/assets/3219885/837012/e9ac99be-f2fd-11e2-9ee3-ffd8c5a45079.png)
Learn
![learn_icon](https://f.cloud.github.com/assets/3219885/837010/e9aab4c8-f2fd-11e2-9d0d-5b142a211106.png)
Connect
![connect_icon](https://f.cloud.github.com/assets/3219885/837011/e9aca422-f2fd-11e2-85b6-517ad9981c2a.png)

**Comment by arielkennan** [comment]
All body text is Open Sans http://www.google.com/fonts/specimen/Open+Sans
Homepage uses bold. Regular will be used elsewhere. 

Colors 
Gray: 585b5b
Orange: ff4000
Light blue: 74bbd4

**Comment by arielkennan** [comment]
CfA white on white logo: 
![cfa_logo_reverse](https://f.cloud.github.com/assets/3219885/843910/c6ec65c8-f3c8-11e2-8182-3c430f70d631.png)

**Comment by arielkennan** [comment]
Revised PNG
![bizfriendly_weblogo](https://f.cloud.github.com/assets/3219885/844092/0ea74786-f3cc-11e2-81cf-f05c4c7ac564.png)
