### ISSUE TITLE
Implement share functionality

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#36]
Created an account for us on AddThis. Now need to use their API/SDK to link our custom buttons to their tools.

**Comment by arielkennan** [comment]
I think the Share Endpoints will work easily: http://support.addthis.com/customer/portal/articles/381265-addthis-sharing-endpoints#.UgQ9zGRAQ9F

Also really like that we can write the custom text in here for Twitter, i.e. "I created a Facebook page for my business using @Bizfriendly. Try it out now http://bizfriendly.com/lessons/blahblahblah"

**Comment by ondrae** [comment]
All of these are live. The Twitter one still says "I created a Facebook Page" even on the Foursquare lesson.
