### ISSUE TITLE
Lag time in app starting

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#39]
#### Description

Every so often the api takes a while to respond. Lets have a loading animation while we wait for a response. This is different than the _stepTransition animation while loading the next step.
#### Files

learn.html, lesson.html, instructions.html
#### Tips
- [x] On load start the animation. 
- [x] When the api call completes, replace the animation with the content.

**Comment by arielkennan** [comment]
Add loading icon as a front end work around. Animated gif (100x100): 

![output_nl8evf](https://f.cloud.github.com/assets/3219885/943573/1e115e00-0231-11e3-864d-157370072632.gif)
