### ISSUE TITLE
Create the Learn Landing Page

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#4]
#### Description

Following the wireframe, we need to code the Learn landing page. No design love yet, we just need all the various divs and whatnot to exist.
#### Files

learn.html
#### Tools Needed

HTML, CSS, JQuery, Bootstrap
#### Screenshot

![htc_learnlanding071213](https://f.cloud.github.com/assets/3219885/791107/8c772532-eb39-11e2-9c44-b53feccab658.jpg)
#### Tips
- [ ] Use $.getJSON to call http://howtocity.herokuapp.com/api/v1/categories
- [ ] Sort the lessons by Category
- [ ] Arrange the lessons in a collapsable table using http://twitter.github.io/bootstrap/javascript.html#collapse

**Comment by arielkennan** [comment]
In progress visual design 
![bizfriendly_learnlanding_072513](https://f.cloud.github.com/assets/3219885/859185/e3a3a7ca-f577-11e2-8324-cc633c45853c.png)

**Comment by arielkennan** [comment]
Updated visual design: 
![bizfriendly_learnlanding_072513](https://f.cloud.github.com/assets/3219885/859802/e5cda174-f589-11e2-9f77-0c93bba2664e.gif)

Icons: 
![fb_gray](https://f.cloud.github.com/assets/3219885/859784/a2043fb6-f589-11e2-9509-c80486eef98f.gif)
![learnicon_gray](https://f.cloud.github.com/assets/3219885/859786/a6211f42-f589-11e2-9873-73cf94baf27e.gif)
