### ISSUE TITLE
Create the Lesson Landing Page

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#5]
#### Description

Following the wireframe, we need to code the Lesson landing page. It is a template that will be used for every lesson on the site. 
No design love yet, we just need all the various divs and whatnot to exist.
#### Files

lessons.html
#### Tools Needed

HTML, CSS, JQuery, Bootstrap
#### Screenshot

![htc_lessonlanding071213](https://f.cloud.github.com/assets/3219885/791133/210ef936-eb3a-11e2-886d-5b01d3f36d4d.jpg)
#### Tips
- [ ] Use $.getJSON to call http://howtocity.herokuapp.com/api/v1/lessons/1

**Comment by arielkennan** [comment]
![bizfriendly_lessonlanding_072513](https://f.cloud.github.com/assets/3219885/860157/c0f76316-f599-11e2-83a8-d5f76237c47d.gif)
