### ISSUE TITLE
Site doesn't work in IE 9

### ISSUE THREAD

**Issue by ondrae** [codeforamerica/bizfriendly-web#64]
#### Description

Our site doesn't operate in IE9. This is due to our heavy reliance on jQuery. They claim to support IE9 though, so there must be work arounds for all of our issues.
#### Issues
- Learn page doesn't load content.
- Instructions don't work.
- Sign Up process doesn't work
- Sign In process doesn't work.
#### Skills Needed

jQuery, Thick Forehead
#### Tips
- [ ] Detect IE9 and alert users that it doesn't work.
- [ ] Decide if we need to support it.
- [ ] Quit the Fellowship if we do.

**Comment by anselmbradford** [comment]
I've been battling IE issues on our project for a bit, though it's been IE8 mainly... here are some tips:

---

Add this in your head section to suppress JavaScript errors in IE that stop the page from loading:

```
    <!--[if lt IE 9]>
    <script type="text/javascript">
      // patch to handle suppression of JS errors in IE
      window.onerror=function(){return true;};
    </script>
    <![endif]-->
```

This may or may not be preferable, but if the content is still accessible with JS turned off, this is good to include.

---

The console in IE9 should give you a (usually generic) error that you can click to go to the respective code. Look at the method calls around where it brings you in the code and do google searches for browser support of those methods. For instance, I needed to polyfill the `trim` method onto the `String` object, which if I recall was an error that arose from jQuery code.

---

After performing the above, check the Modernizr wiki for polyfills:

https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills

The most common ones I run into in my development are lack of support for `addEventListener` and `classList` (in IE8 though).

**Comment by ondrae** [comment]
Thanks @anselmbradford I'll check it out and come to you for advice when I start on this issue.

**Comment by ondrae** [comment]
@anselmbradford That list of Polyfills totally just saved me! I just spent days writing separate code for my site on IE9. The XDomain polyfill on there works where all other jQuery plugins and the like failed. Thanks!
