### ISSUE TITLE
Implement new Learn landing page

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#82]
icons to come
![bizfriendly_learnlanding_091913](https://f.cloud.github.com/assets/3219885/1220227/6973bbe8-26d7-11e3-8424-37ec1c7f2128.gif)

**Comment by ty10r** [comment]
I always wondered by the learn page had multiple columns, I'm glad they're consolidating.

Are the small blue links to categories here meant to jump to a category? If the page only has a small amount of lessons listed per category, that will be largely useless. If the page has a large amount of lessons listed per category, you would be left with a crazy long list of lessons in a grid with nothing but a few small links and 'back to top' to navigate it.

Have you considered making this a list of Categories where clicking the header of the category would show/hide its description and most popular lessons?

@arielkennan @ondrae

**Comment by arielkennan** [comment]
Thanks for your thoughts on this, @ty10r! The blue links will jump to a category. We heard in user testing that business owners wanted to see all of the skills easily as well as their accompanying information without having to click to see it. You'll also see that we changed the architecture a little on how we were organizing formation. It's now Skill category > web service > lessons, so that you no longer get individual lessons on the Learn landing page. You're right that until that there's much content, that the blue will be a stack on top and have no need for "back to top." We're kind of in a balancing mode at the moment with what our launch content will be and our full vision. Also thinking a lot about sustainability and what needs to be there to support a quickly growing content set.
