### ISSUE TITLE
Implement Connect landing page

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#86]
![bizfriendly_connectlanding_100113](https://f.cloud.github.com/assets/3219885/1249953/eead0816-2aea-11e3-9c75-49e11bdfee76.gif)

**Comment by arielkennan** [comment]
Re-opening for implementation of styling of the Connect page based on this mockup.

**Comment by ondrae** [comment]
@arielkennan This is up on Staging, check it out. It was harder than it should have been to get the business names in there.

**Comment by arielkennan** [comment]
Looking great! 
- I'm seeing remnants of the profile show up when not logged in before the page fully loads? On pretty slow Wi-Fi at the moment so that might have something to do with it too. 

A few tweaks: 
- top green line of text should say "Here's where you can see what the BizFriend.ly community is learning and teaching." Should have a gray line below that says "Check out what everyone is up to and help cheer on fellow business owners!"
- In the leader boards user names should be Open Sans bold. 
- The entire line in the Recent Activity should be Open Sans bold. 
- add a little more padding between Top Learns and Top Teachers and the line below
- is there an easy way to get the leader boards to not include the BizFriend.ly admin account? We'll always be at the top :laughing: 
- on profile page: shouldn't automatically say "hi" if it's not your profile. Maybe we should just take the hi out?
