### ISSUE TITLE
Create the lesson step type variations

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#9]
#### Description

Following the wireframe, we need to code the variations in different types of steps.
No design love yet, we just need all the various divs and whatnot to exist.
#### Tools Needed

HTML, CSS, JQuery, Bootstrap
#### Screenshot

![htc_lessonwireframes_071213](https://f.cloud.github.com/assets/3219885/791178/40730604-eb3b-11e2-8f63-76ae9860cb69.jpg)
![htc_lessonwireframes_0712134](https://f.cloud.github.com/assets/3219885/791179/446a1e78-eb3b-11e2-933b-ceca17517d99.jpg)

**Comment by arielkennan** [comment]
Visual design progress: 
Text Only
![bizfriendly_lessonsteps_text_072513](https://f.cloud.github.com/assets/3219885/860582/5088d650-f5ad-11e2-8e81-9e560f22da14.gif)

Text + Button
![bizfriendly_lessonsteps_textbutton_072513](https://f.cloud.github.com/assets/3219885/860583/56b4d16e-f5ad-11e2-8cb5-628195626793.gif)

Text + Text Field 
![bizfriendly_lessonsteps_textfield_072513](https://f.cloud.github.com/assets/3219885/860584/591ce18a-f5ad-11e2-9689-dc050ceffd51.gif)

Text + Image
![bizfriendly_lessonsteps_teximaget_072513](https://f.cloud.github.com/assets/3219885/860585/6f1ca1dc-f5ad-11e2-8796-9bf8d3d5c619.gif)

Celebration
![bizfriendly_lessonsteps_celebration_072513](https://f.cloud.github.com/assets/3219885/860586/795d3224-f5ad-11e2-855e-068b86bbafd0.gif)

**Comment by ondrae** [comment]
@arielkennan You have these icons available?

**Comment by arielkennan** [comment]
Social Icons
![fb_orange](https://f.cloud.github.com/assets/3219885/921379/13c875a6-fef7-11e2-80ad-9a9bc9b6d68e.gif)
![twitter_orange](https://f.cloud.github.com/assets/3219885/921385/22588c28-fef7-11e2-8072-0e78d316bb96.gif)
![gplus_orange](https://f.cloud.github.com/assets/3219885/921387/25e0e57a-fef7-11e2-8f8a-5372bc22802a.gif)
![linkedin_orange](https://f.cloud.github.com/assets/3219885/921389/281edc20-fef7-11e2-9df8-c82c028d779c.gif) (switched Pinterest to LinkedIn)

See celebration icons in #16
