### ISSUE TITLE
Lesson builder: image duplicate

### ISSUE THREAD

**Issue by arielkennan** [codeforamerica/bizfriendly-web#98]
When you add a second image within a lesson but on a different step, it shows both images once you finished the upload. 

Steps to reproduce: 
- Create new lesson 
- Add step with image 
- Add new step
- Upload image to that new step
- See both images appear

**Comment by ondrae** [comment]
When uploading an image, it gets added to all the image-upload divs. Its should only be added to the visible one in the lesson builder.
